"""add age column

Revision ID: 46272dc2550c
Revises: 0c5faf7ac21c
Create Date: 2021-06-17 11:44:29.386001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46272dc2550c'
down_revision = '0c5faf7ac21c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
